version: '3.7'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ../../../efs:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=${RDS_HOST}
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_CONFIG_EXTRA=define('WP_HOME','${LB_DNS}');
volumes:
  db_data:
