version: '3.7'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ../../../efs:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wordpress.cmy4dyh31mfn.eu-west-3.rds.amazonaws.com
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOME=newest-1-1771759872.eu-west-3.elb.amazonaws.com
      - WORDPRESS_CONFIG_EXTRA=define('WP_HOME','newest-1-1771759872.eu-west-3.elb.amazonaws.com');
volumes:
  db_data:
